name: GitHub Contribution Calendar Snake Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: '0 0 * * 1-5'

  # Allow manual triggering of the workflow
  workflow_dispatch:


jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animations
      - name: Generate GitHub Contribution Calendar Snake Animations
        uses: Platane/snk@v3
        with:
          # GitHub username to generate the animation for
          github_user_name: ${{ github.repository_owner }}

          # Define the output files and their configurations
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Commit and Push to Main Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Update snake animation [skip ci]" || echo "No changes to commit"
          git push origin main
